// <auto-generated/>
namespace Evo.GUI.Winforms
{
    public partial class FrmMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
            System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
            System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmMain));
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.groupBox2 = new System.Windows.Forms.GroupBox();
            this.btnNewWorld = new System.Windows.Forms.Button();
            this.chkVisualize = new System.Windows.Forms.CheckBox();
            this.label1 = new System.Windows.Forms.Label();
            this.numSpeed = new System.Windows.Forms.NumericUpDown();
            this.btnToggleTimer = new System.Windows.Forms.Button();
            this.btn1Step = new System.Windows.Forms.Button();
            this.tabView = new System.Windows.Forms.TabControl();
            this.tabStats = new System.Windows.Forms.TabPage();
            this.splitContainer3 = new System.Windows.Forms.SplitContainer();
            this.chtPopulation = new System.Windows.Forms.DataVisualization.Charting.Chart();
            this.txtStats = new System.Windows.Forms.TextBox();
            this.tabTune = new System.Windows.Forms.TabPage();
            this.tabUnit = new System.Windows.Forms.TabPage();
            this.splitContainer2 = new System.Windows.Forms.SplitContainer();
            this.txtUnit = new System.Windows.Forms.TextBox();
            this.txtAverageUnit = new System.Windows.Forms.TextBox();
            this.tabPage4 = new System.Windows.Forms.TabPage();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.rbDiffFromAverage = new System.Windows.Forms.RadioButton();
            this.rbSightRange = new System.Windows.Forms.RadioButton();
            this.rbMinEneryAcceptable = new System.Windows.Forms.RadioButton();
            this.rbPurpose = new System.Windows.Forms.RadioButton();
            this.rbFertility = new System.Windows.Forms.RadioButton();
            this.rbLifeTime = new System.Windows.Forms.RadioButton();
            this.rbAggression = new System.Windows.Forms.RadioButton();
            this.rbStrength = new System.Windows.Forms.RadioButton();
            this.rbDesire = new System.Windows.Forms.RadioButton();
            this.rbEnergy = new System.Windows.Forms.RadioButton();
            this.rbColor = new System.Windows.Forms.RadioButton();
            this.rbAge = new System.Windows.Forms.RadioButton();
            this.button1 = new System.Windows.Forms.Button();
            this.tabEditWorld = new System.Windows.Forms.TabPage();
            this.groupBox3 = new System.Windows.Forms.GroupBox();
            this.chkRemoveWall = new System.Windows.Forms.CheckBox();
            this.chkHorizontalWall = new System.Windows.Forms.CheckBox();
            this.chkVerticalWall = new System.Windows.Forms.CheckBox();
            this.Map = new System.Windows.Forms.PictureBox();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.bgColorDialog = new System.Windows.Forms.ColorDialog();
            this.tipVerticalWall = new System.Windows.Forms.ToolTip(this.components);
            this.tipHorizontalWall = new System.Windows.Forms.ToolTip(this.components);
            this.tipRemoveWall = new System.Windows.Forms.ToolTip(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numSpeed)).BeginInit();
            this.tabView.SuspendLayout();
            this.tabStats.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).BeginInit();
            this.splitContainer3.Panel1.SuspendLayout();
            this.splitContainer3.Panel2.SuspendLayout();
            this.splitContainer3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.chtPopulation)).BeginInit();
            this.tabUnit.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).BeginInit();
            this.splitContainer2.Panel1.SuspendLayout();
            this.splitContainer2.Panel2.SuspendLayout();
            this.splitContainer2.SuspendLayout();
            this.tabPage4.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.tabEditWorld.SuspendLayout();
            this.groupBox3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Map)).BeginInit();
            this.SuspendLayout();
            // 
            // splitContainer1
            // 
            this.splitContainer1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer1.Location = new System.Drawing.Point(0, 0);
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.groupBox2);
            this.splitContainer1.Panel1.Controls.Add(this.tabView);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.AutoScroll = true;
            this.splitContainer1.Panel2.Controls.Add(this.Map);
            this.splitContainer1.Size = new System.Drawing.Size(1509, 802);
            this.splitContainer1.SplitterDistance = 365;
            this.splitContainer1.TabIndex = 0;
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.groupBox2.Controls.Add(this.btnNewWorld);
            this.groupBox2.Controls.Add(this.chkVisualize);
            this.groupBox2.Controls.Add(this.label1);
            this.groupBox2.Controls.Add(this.numSpeed);
            this.groupBox2.Controls.Add(this.btnToggleTimer);
            this.groupBox2.Controls.Add(this.btn1Step);
            this.groupBox2.Location = new System.Drawing.Point(7, 3);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(351, 80);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Control";
            // 
            // btnNewWorld
            // 
            this.btnNewWorld.Location = new System.Drawing.Point(258, 19);
            this.btnNewWorld.Name = "btnNewWorld";
            this.btnNewWorld.Size = new System.Drawing.Size(86, 23);
            this.btnNewWorld.TabIndex = 5;
            this.btnNewWorld.Text = "New World";
            this.btnNewWorld.UseVisualStyleBackColor = true;
            this.btnNewWorld.Click += new System.EventHandler(this.btnNewWorld_Click);
            // 
            // chkVisualize
            // 
            this.chkVisualize.AutoSize = true;
            this.chkVisualize.Checked = true;
            this.chkVisualize.CheckState = System.Windows.Forms.CheckState.Checked;
            this.chkVisualize.Location = new System.Drawing.Point(98, 52);
            this.chkVisualize.Name = "chkVisualize";
            this.chkVisualize.Size = new System.Drawing.Size(67, 17);
            this.chkVisualize.TabIndex = 4;
            this.chkVisualize.Text = "Vizualize";
            this.chkVisualize.UseVisualStyleBackColor = true;
            this.chkVisualize.CheckedChanged += new System.EventHandler(this.chkVisualize_CheckedChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(175, 54);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(38, 13);
            this.label1.TabIndex = 3;
            this.label1.Text = "Speed";
            // 
            // numSpeed
            // 
            this.numSpeed.Location = new System.Drawing.Point(219, 51);
            this.numSpeed.Maximum = new decimal(new int[] {
            9,
            0,
            0,
            0});
            this.numSpeed.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numSpeed.Name = "numSpeed";
            this.numSpeed.Size = new System.Drawing.Size(36, 20);
            this.numSpeed.TabIndex = 2;
            this.numSpeed.Value = new decimal(new int[] {
            8,
            0,
            0,
            0});
            this.numSpeed.ValueChanged += new System.EventHandler(this.numSpeed_ValueChanged);
            // 
            // btnToggleTimer
            // 
            this.btnToggleTimer.Location = new System.Drawing.Point(6, 48);
            this.btnToggleTimer.Name = "btnToggleTimer";
            this.btnToggleTimer.Size = new System.Drawing.Size(86, 23);
            this.btnToggleTimer.TabIndex = 1;
            this.btnToggleTimer.Text = "Start Timer";
            this.btnToggleTimer.UseVisualStyleBackColor = true;
            this.btnToggleTimer.Click += new System.EventHandler(this.btnToggleTimer_Click);
            // 
            // btn1Step
            // 
            this.btn1Step.Location = new System.Drawing.Point(6, 19);
            this.btn1Step.Name = "btn1Step";
            this.btn1Step.Size = new System.Drawing.Size(86, 23);
            this.btn1Step.TabIndex = 0;
            this.btn1Step.Text = "One Step";
            this.btn1Step.UseVisualStyleBackColor = true;
            this.btn1Step.Click += new System.EventHandler(this.btn1Step_Click);
            // 
            // tabView
            // 
            this.tabView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabView.Controls.Add(this.tabStats);
            this.tabView.Controls.Add(this.tabTune);
            this.tabView.Controls.Add(this.tabUnit);
            this.tabView.Controls.Add(this.tabPage4);
            this.tabView.Controls.Add(this.tabEditWorld);
            this.tabView.Location = new System.Drawing.Point(0, 89);
            this.tabView.Name = "tabView";
            this.tabView.SelectedIndex = 0;
            this.tabView.Size = new System.Drawing.Size(358, 713);
            this.tabView.TabIndex = 0;
            // 
            // tabStats
            // 
            this.tabStats.Controls.Add(this.splitContainer3);
            this.tabStats.Location = new System.Drawing.Point(4, 22);
            this.tabStats.Name = "tabStats";
            this.tabStats.Padding = new System.Windows.Forms.Padding(3);
            this.tabStats.Size = new System.Drawing.Size(350, 687);
            this.tabStats.TabIndex = 1;
            this.tabStats.Text = "Stats";
            this.tabStats.UseVisualStyleBackColor = true;
            // 
            // splitContainer3
            // 
            this.splitContainer3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer3.Location = new System.Drawing.Point(3, 3);
            this.splitContainer3.Name = "splitContainer3";
            this.splitContainer3.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer3.Panel1
            // 
            this.splitContainer3.Panel1.Controls.Add(this.chtPopulation);
            // 
            // splitContainer3.Panel2
            // 
            this.splitContainer3.Panel2.Controls.Add(this.txtStats);
            this.splitContainer3.Size = new System.Drawing.Size(344, 681);
            this.splitContainer3.SplitterDistance = 340;
            this.splitContainer3.TabIndex = 2;
            // 
            // chtPopulation
            // 
            chartArea1.Name = "ChartArea1";
            this.chtPopulation.ChartAreas.Add(chartArea1);
            this.chtPopulation.Dock = System.Windows.Forms.DockStyle.Fill;
            legend1.Name = "Legend1";
            this.chtPopulation.Legends.Add(legend1);
            this.chtPopulation.Location = new System.Drawing.Point(0, 0);
            this.chtPopulation.Name = "chtPopulation";
            series1.ChartArea = "ChartArea1";
            series1.Legend = "Legend1";
            series1.Name = "Series1";
            this.chtPopulation.Series.Add(series1);
            this.chtPopulation.Size = new System.Drawing.Size(344, 340);
            this.chtPopulation.TabIndex = 1;
            this.chtPopulation.TabStop = false;
            this.chtPopulation.Text = "Population";
            // 
            // txtStats
            // 
            this.txtStats.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtStats.Font = new System.Drawing.Font("Consolas", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.txtStats.Location = new System.Drawing.Point(0, 0);
            this.txtStats.Multiline = true;
            this.txtStats.Name = "txtStats";
            this.txtStats.ReadOnly = true;
            this.txtStats.Size = new System.Drawing.Size(344, 337);
            this.txtStats.TabIndex = 0;
            // 
            // tabTune
            // 
            this.tabTune.AutoScroll = true;
            this.tabTune.Location = new System.Drawing.Point(4, 22);
            this.tabTune.Name = "tabTune";
            this.tabTune.Padding = new System.Windows.Forms.Padding(3);
            this.tabTune.Size = new System.Drawing.Size(350, 687);
            this.tabTune.TabIndex = 4;
            this.tabTune.Text = "Tune";
            this.tabTune.UseVisualStyleBackColor = true;
            // 
            // tabUnit
            // 
            this.tabUnit.Controls.Add(this.splitContainer2);
            this.tabUnit.Location = new System.Drawing.Point(4, 22);
            this.tabUnit.Name = "tabUnit";
            this.tabUnit.Padding = new System.Windows.Forms.Padding(3);
            this.tabUnit.Size = new System.Drawing.Size(350, 687);
            this.tabUnit.TabIndex = 2;
            this.tabUnit.Text = "Unit";
            this.tabUnit.UseVisualStyleBackColor = true;
            // 
            // splitContainer2
            // 
            this.splitContainer2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainer2.Location = new System.Drawing.Point(3, 3);
            this.splitContainer2.Name = "splitContainer2";
            this.splitContainer2.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // splitContainer2.Panel1
            // 
            this.splitContainer2.Panel1.Controls.Add(this.txtUnit);
            // 
            // splitContainer2.Panel2
            // 
            this.splitContainer2.Panel2.Controls.Add(this.txtAverageUnit);
            this.splitContainer2.Size = new System.Drawing.Size(344, 681);
            this.splitContainer2.SplitterDistance = 307;
            this.splitContainer2.TabIndex = 1;
            // 
            // txtUnit
            // 
            this.txtUnit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtUnit.Font = new System.Drawing.Font("Consolas", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.txtUnit.Location = new System.Drawing.Point(0, 0);
            this.txtUnit.Multiline = true;
            this.txtUnit.Name = "txtUnit";
            this.txtUnit.ReadOnly = true;
            this.txtUnit.Size = new System.Drawing.Size(344, 307);
            this.txtUnit.TabIndex = 0;
            this.txtUnit.TabStop = false;
            this.txtUnit.Text = "<Click on a unit to get its info>";
            // 
            // txtAverageUnit
            // 
            this.txtAverageUnit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.txtAverageUnit.Font = new System.Drawing.Font("Consolas", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.txtAverageUnit.Location = new System.Drawing.Point(0, 0);
            this.txtAverageUnit.Multiline = true;
            this.txtAverageUnit.Name = "txtAverageUnit";
            this.txtAverageUnit.ReadOnly = true;
            this.txtAverageUnit.Size = new System.Drawing.Size(344, 370);
            this.txtAverageUnit.TabIndex = 1;
            this.txtAverageUnit.TabStop = false;
            // 
            // tabPage4
            // 
            this.tabPage4.Controls.Add(this.groupBox1);
            this.tabPage4.Controls.Add(this.button1);
            this.tabPage4.Location = new System.Drawing.Point(4, 22);
            this.tabPage4.Name = "tabPage4";
            this.tabPage4.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage4.Size = new System.Drawing.Size(350, 687);
            this.tabPage4.TabIndex = 3;
            this.tabPage4.Text = "View";
            this.tabPage4.UseVisualStyleBackColor = true;
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.rbDiffFromAverage);
            this.groupBox1.Controls.Add(this.rbSightRange);
            this.groupBox1.Controls.Add(this.rbMinEneryAcceptable);
            this.groupBox1.Controls.Add(this.rbPurpose);
            this.groupBox1.Controls.Add(this.rbFertility);
            this.groupBox1.Controls.Add(this.rbLifeTime);
            this.groupBox1.Controls.Add(this.rbAggression);
            this.groupBox1.Controls.Add(this.rbStrength);
            this.groupBox1.Controls.Add(this.rbDesire);
            this.groupBox1.Controls.Add(this.rbEnergy);
            this.groupBox1.Controls.Add(this.rbColor);
            this.groupBox1.Controls.Add(this.rbAge);
            this.groupBox1.Location = new System.Drawing.Point(8, 35);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(164, 300);
            this.groupBox1.TabIndex = 4;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Show";
            // 
            // rbDiffFromAverage
            // 
            this.rbDiffFromAverage.AutoSize = true;
            this.rbDiffFromAverage.Location = new System.Drawing.Point(6, 272);
            this.rbDiffFromAverage.Name = "rbDiffFromAverage";
            this.rbDiffFromAverage.Size = new System.Drawing.Size(143, 17);
            this.rbDiffFromAverage.TabIndex = 12;
            this.rbDiffFromAverage.Text = "Difference From Average";
            this.rbDiffFromAverage.UseVisualStyleBackColor = true;
            // 
            // rbSightRange
            // 
            this.rbSightRange.AutoSize = true;
            this.rbSightRange.Location = new System.Drawing.Point(6, 226);
            this.rbSightRange.Name = "rbSightRange";
            this.rbSightRange.Size = new System.Drawing.Size(84, 17);
            this.rbSightRange.TabIndex = 11;
            this.rbSightRange.Text = "Sight Range";
            this.rbSightRange.UseVisualStyleBackColor = true;
            this.rbSightRange.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbMinEneryAcceptable
            // 
            this.rbMinEneryAcceptable.AutoSize = true;
            this.rbMinEneryAcceptable.Location = new System.Drawing.Point(6, 249);
            this.rbMinEneryAcceptable.Name = "rbMinEneryAcceptable";
            this.rbMinEneryAcceptable.Size = new System.Drawing.Size(135, 17);
            this.rbMinEneryAcceptable.TabIndex = 10;
            this.rbMinEneryAcceptable.Text = "Min Energy Acceptable";
            this.rbMinEneryAcceptable.UseVisualStyleBackColor = true;
            this.rbMinEneryAcceptable.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbPurpose
            // 
            this.rbPurpose.AutoSize = true;
            this.rbPurpose.Location = new System.Drawing.Point(6, 203);
            this.rbPurpose.Name = "rbPurpose";
            this.rbPurpose.Size = new System.Drawing.Size(64, 17);
            this.rbPurpose.TabIndex = 9;
            this.rbPurpose.Text = "Purpose";
            this.rbPurpose.UseVisualStyleBackColor = true;
            this.rbPurpose.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbFertility
            // 
            this.rbFertility.AutoSize = true;
            this.rbFertility.Location = new System.Drawing.Point(6, 180);
            this.rbFertility.Name = "rbFertility";
            this.rbFertility.Size = new System.Drawing.Size(57, 17);
            this.rbFertility.TabIndex = 8;
            this.rbFertility.Text = "Fertility";
            this.rbFertility.UseVisualStyleBackColor = true;
            this.rbFertility.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbLifeTime
            // 
            this.rbLifeTime.AutoSize = true;
            this.rbLifeTime.Location = new System.Drawing.Point(6, 157);
            this.rbLifeTime.Name = "rbLifeTime";
            this.rbLifeTime.Size = new System.Drawing.Size(68, 17);
            this.rbLifeTime.TabIndex = 7;
            this.rbLifeTime.Text = "Life Time";
            this.rbLifeTime.UseVisualStyleBackColor = true;
            this.rbLifeTime.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbAggression
            // 
            this.rbAggression.AutoSize = true;
            this.rbAggression.Location = new System.Drawing.Point(6, 111);
            this.rbAggression.Name = "rbAggression";
            this.rbAggression.Size = new System.Drawing.Size(77, 17);
            this.rbAggression.TabIndex = 6;
            this.rbAggression.Text = "Aggression";
            this.rbAggression.UseVisualStyleBackColor = true;
            this.rbAggression.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbStrength
            // 
            this.rbStrength.AutoSize = true;
            this.rbStrength.Location = new System.Drawing.Point(6, 134);
            this.rbStrength.Name = "rbStrength";
            this.rbStrength.Size = new System.Drawing.Size(65, 17);
            this.rbStrength.TabIndex = 5;
            this.rbStrength.Text = "Strength";
            this.rbStrength.UseVisualStyleBackColor = true;
            this.rbStrength.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbDesire
            // 
            this.rbDesire.AutoSize = true;
            this.rbDesire.Location = new System.Drawing.Point(6, 88);
            this.rbDesire.Name = "rbDesire";
            this.rbDesire.Size = new System.Drawing.Size(55, 17);
            this.rbDesire.TabIndex = 4;
            this.rbDesire.Text = "Desire";
            this.rbDesire.UseVisualStyleBackColor = true;
            this.rbDesire.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbEnergy
            // 
            this.rbEnergy.AutoSize = true;
            this.rbEnergy.Location = new System.Drawing.Point(6, 65);
            this.rbEnergy.Name = "rbEnergy";
            this.rbEnergy.Size = new System.Drawing.Size(58, 17);
            this.rbEnergy.TabIndex = 2;
            this.rbEnergy.Text = "Energy";
            this.rbEnergy.UseVisualStyleBackColor = true;
            this.rbEnergy.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbColor
            // 
            this.rbColor.AutoSize = true;
            this.rbColor.Checked = true;
            this.rbColor.Location = new System.Drawing.Point(6, 19);
            this.rbColor.Name = "rbColor";
            this.rbColor.Size = new System.Drawing.Size(49, 17);
            this.rbColor.TabIndex = 1;
            this.rbColor.TabStop = true;
            this.rbColor.Text = "Color";
            this.rbColor.UseVisualStyleBackColor = true;
            this.rbColor.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // rbAge
            // 
            this.rbAge.AutoSize = true;
            this.rbAge.Location = new System.Drawing.Point(6, 42);
            this.rbAge.Name = "rbAge";
            this.rbAge.Size = new System.Drawing.Size(44, 17);
            this.rbAge.TabIndex = 3;
            this.rbAge.Text = "Age";
            this.rbAge.UseVisualStyleBackColor = true;
            this.rbAge.CheckedChanged += new System.EventHandler(this.rbViewColor_CheckedChanged);
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(8, 6);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(164, 23);
            this.button1.TabIndex = 0;
            this.button1.Text = "Change background color";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // tabEditWorld
            // 
            this.tabEditWorld.Controls.Add(this.groupBox3);
            this.tabEditWorld.Location = new System.Drawing.Point(4, 22);
            this.tabEditWorld.Name = "tabEditWorld";
            this.tabEditWorld.Padding = new System.Windows.Forms.Padding(3);
            this.tabEditWorld.Size = new System.Drawing.Size(350, 687);
            this.tabEditWorld.TabIndex = 5;
            this.tabEditWorld.Text = "Edit world";
            this.tabEditWorld.UseVisualStyleBackColor = true;
            // 
            // groupBox3
            // 
            this.groupBox3.Controls.Add(this.chkRemoveWall);
            this.groupBox3.Controls.Add(this.chkHorizontalWall);
            this.groupBox3.Controls.Add(this.chkVerticalWall);
            this.groupBox3.Location = new System.Drawing.Point(9, 6);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new System.Drawing.Size(139, 67);
            this.groupBox3.TabIndex = 1;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Walls";
            // 
            // chkRemoveWall
            // 
            this.chkRemoveWall.Appearance = System.Windows.Forms.Appearance.Button;
            this.chkRemoveWall.AutoSize = true;
            this.chkRemoveWall.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.chkRemoveWall.ForeColor = System.Drawing.Color.DarkRed;
            this.chkRemoveWall.Location = new System.Drawing.Point(92, 19);
            this.chkRemoveWall.MinimumSize = new System.Drawing.Size(35, 35);
            this.chkRemoveWall.Name = "chkRemoveWall";
            this.chkRemoveWall.Size = new System.Drawing.Size(35, 35);
            this.chkRemoveWall.TabIndex = 2;
            this.chkRemoveWall.Text = "x";
            this.chkRemoveWall.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tipRemoveWall.SetToolTip(this.chkRemoveWall, "Click on an existing wall to remove it");
            this.chkRemoveWall.UseVisualStyleBackColor = true;
            this.chkRemoveWall.CheckedChanged += new System.EventHandler(this.chkRemoveWall_CheckedChanged);
            this.chkRemoveWall.Click += new System.EventHandler(this.chkRemoveWall_Click);
            // 
            // chkHorizontalWall
            // 
            this.chkHorizontalWall.Appearance = System.Windows.Forms.Appearance.Button;
            this.chkHorizontalWall.AutoSize = true;
            this.chkHorizontalWall.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.chkHorizontalWall.Location = new System.Drawing.Point(47, 19);
            this.chkHorizontalWall.MinimumSize = new System.Drawing.Size(35, 35);
            this.chkHorizontalWall.Name = "chkHorizontalWall";
            this.chkHorizontalWall.Size = new System.Drawing.Size(35, 35);
            this.chkHorizontalWall.TabIndex = 1;
            this.chkHorizontalWall.Text = "—";
            this.chkHorizontalWall.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tipVerticalWall.SetToolTip(this.chkHorizontalWall, "Add a vertical wall");
            this.chkHorizontalWall.UseVisualStyleBackColor = true;
            this.chkHorizontalWall.Click += new System.EventHandler(this.chkHorizontalWall_Click);
            // 
            // chkVerticalWall
            // 
            this.chkVerticalWall.Appearance = System.Windows.Forms.Appearance.Button;
            this.chkVerticalWall.AutoSize = true;
            this.chkVerticalWall.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.chkVerticalWall.Location = new System.Drawing.Point(6, 19);
            this.chkVerticalWall.MinimumSize = new System.Drawing.Size(35, 35);
            this.chkVerticalWall.Name = "chkVerticalWall";
            this.chkVerticalWall.Size = new System.Drawing.Size(35, 35);
            this.chkVerticalWall.TabIndex = 0;
            this.chkVerticalWall.Text = "|";
            this.chkVerticalWall.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tipVerticalWall.SetToolTip(this.chkVerticalWall, "Add a vertical wall");
            this.chkVerticalWall.UseVisualStyleBackColor = true;
            this.chkVerticalWall.Click += new System.EventHandler(this.chkVerticalWall_Click);
            // 
            // Map
            // 
            this.Map.Location = new System.Drawing.Point(0, 0);
            this.Map.Name = "Map";
            this.Map.Size = new System.Drawing.Size(1140, 802);
            this.Map.TabIndex = 0;
            this.Map.TabStop = false;
            this.Map.Click += new System.EventHandler(this.Map_Click);
            this.Map.Paint += new System.Windows.Forms.PaintEventHandler(this.Map_Paint_1);
            this.Map.MouseClick += new System.Windows.Forms.MouseEventHandler(this.Map_MouseClick);
            this.Map.MouseEnter += new System.EventHandler(this.Map_MouseEnter);
            this.Map.MouseMove += new System.Windows.Forms.MouseEventHandler(this.Map_MouseMove);
            // 
            // timer1
            // 
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // tipVerticalWall
            // 
            this.tipVerticalWall.ToolTipTitle = "Vertical wall";
            // 
            // tipHorizontalWall
            // 
            this.tipHorizontalWall.ToolTipTitle = "Horizontal wall";
            // 
            // tipRemoveWall
            // 
            this.tipRemoveWall.ToolTipTitle = "Remove a wall";
            // 
            // FrmMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1509, 802);
            this.Controls.Add(this.splitContainer1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "FrmMain";
            this.Text = "Evo";
            this.Load += new System.EventHandler(this.FrmMain_Load);
            this.Shown += new System.EventHandler(this.FrmMain_Shown);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numSpeed)).EndInit();
            this.tabView.ResumeLayout(false);
            this.tabStats.ResumeLayout(false);
            this.splitContainer3.Panel1.ResumeLayout(false);
            this.splitContainer3.Panel2.ResumeLayout(false);
            this.splitContainer3.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer3)).EndInit();
            this.splitContainer3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.chtPopulation)).EndInit();
            this.tabUnit.ResumeLayout(false);
            this.splitContainer2.Panel1.ResumeLayout(false);
            this.splitContainer2.Panel1.PerformLayout();
            this.splitContainer2.Panel2.ResumeLayout(false);
            this.splitContainer2.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer2)).EndInit();
            this.splitContainer2.ResumeLayout(false);
            this.tabPage4.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.tabEditWorld.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Map)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.TabControl tabView;
        private System.Windows.Forms.TabPage tabStats;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.Button btn1Step;
        private System.Windows.Forms.Button btnToggleTimer;
        private System.Windows.Forms.PictureBox Map;
        private System.Windows.Forms.TextBox txtStats;
        private System.Windows.Forms.TabPage tabUnit;
        private System.Windows.Forms.TextBox txtUnit;
        private System.Windows.Forms.TabPage tabPage4;
        private System.Windows.Forms.ColorDialog bgColorDialog;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.RadioButton rbEnergy;
        private System.Windows.Forms.RadioButton rbColor;
        private System.Windows.Forms.RadioButton rbAge;
        private System.Windows.Forms.RadioButton rbSightRange;
        private System.Windows.Forms.RadioButton rbMinEneryAcceptable;
        private System.Windows.Forms.RadioButton rbPurpose;
        private System.Windows.Forms.RadioButton rbFertility;
        private System.Windows.Forms.RadioButton rbLifeTime;
        private System.Windows.Forms.RadioButton rbAggression;
        private System.Windows.Forms.RadioButton rbStrength;
        private System.Windows.Forms.RadioButton rbDesire;
        private System.Windows.Forms.GroupBox groupBox2;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.NumericUpDown numSpeed;
        private System.Windows.Forms.DataVisualization.Charting.Chart chtPopulation;
        private System.Windows.Forms.SplitContainer splitContainer2;
        private System.Windows.Forms.TextBox txtAverageUnit;
        private System.Windows.Forms.SplitContainer splitContainer3;
        private System.Windows.Forms.CheckBox chkVisualize;
        private System.Windows.Forms.TabPage tabTune;
        private System.Windows.Forms.RadioButton rbDiffFromAverage;
        private System.Windows.Forms.Button btnNewWorld;
        private System.Windows.Forms.TabPage tabEditWorld;
        private System.Windows.Forms.CheckBox chkVerticalWall;
        private System.Windows.Forms.GroupBox groupBox3;
        private System.Windows.Forms.CheckBox chkRemoveWall;
        private System.Windows.Forms.CheckBox chkHorizontalWall;
        private System.Windows.Forms.ToolTip tipVerticalWall;
        private System.Windows.Forms.ToolTip tipHorizontalWall;
        private System.Windows.Forms.ToolTip tipRemoveWall;
    }
}

